# NumPy Array complete (by:-wscube Tech)
###### No. of array can be count by viewing no. of square brackets

In [1]:
import numpy as np # once numpy imported then no need to write again and again
x=[1,2,3,4] # list value is passing here
y=np.array(x) # to change list  in array
print(y)

[1 2 3 4]


In [2]:
y # ( without print it gives the type of data also from predefined data)

array([1, 2, 3, 4])

### in the below we taken input as number but we got output as  string value

In [3]:
m=[]# empty list
for i in range(1,5): # range n-1... n=greatest no.as 5
    int_1=input("enter:")
    m.append(int_1) # append means passing the value in list(m)
    print(np.array(m))

enter:3
['3']
enter:3
['3' '3']
enter:3
['3' '3' '3']
enter:3
['3' '3' '3' '3']


In [4]:
import numpy as np
k=[] # a black data is taken and have to fill it by for loop
for i in range(2,7): # range function start from 0(given no.), and run till 4(n-1)
int_0=input("enter")
k.append(Int_0)
print(np.array(k))
print()

IndentationError: expected an indented block (2929453345.py, line 4)

In [ ]:

m=[]# empty list
for i in range(1,5): # range n-1... n=greatest no.
    int_1=int(input("enter:")) # to get input as interger/array
    m.append(int_1) # append means passing the value in list(m)
    print(np.array(m))

In [ ]:
g=[]
for j in range(1,5):
    int_2=int(input("enter your output"))
    g.append(int_2)
    print(np.array(g))

##### Dimension of array
#### 1D aray _ [1 2 3 4],
#### 2D array_[[1 2 2 3]]
#### 3D array_[[[ 3 3 4 5 ]]]
#### Higher Dimension arrays__
##### To detect types of array_j   variable.ndim(x.ndim)


In [ ]:
ar2=np.array([[1,2,3,4],[1,2,3,4,5]])# number of data/items should in both data. as 5 is extra in the given data so output is in list with 1Dimension
print(ar2)
print(ar2.ndim)

In [ ]:
ar2=np.array([[1,2,3,4],[1,2,3,4,]])# number of data/item is same in both data
print(ar2) # to print 
print(ar2.ndim) # To know the 1d,2d,3dimensional

### if having  multiple command to run in a single column then to print use print(file name). otherwise if there is single in the command then write the variable name as it is

In [ ]:
ar3=np.array([[[1,2],[2,3],[4,5]]])
(ar3) # print is not used in this so its not working 
# To find type of array 1d,2d,3d? use .ndim
print(ar3.ndim)

In [ ]:
ar3=np.array([[[2,3],[4,5],[4,3]]])
print(ar3)
print(ar3.ndim) ## here both print & no. of dimension is working

## to print n(10,20,2,)dimension array
### use ndmin=n(10,20,2) to print many no. of array
### use # ndim to detect the type of array(1d,23d,3d,etc

In [ ]:
arn=np.array([1,2,3,4],ndmin=20)# ndmin is use to create dimensional of array
print(arn.ndim) # counting no.of array
print(arn)

### zeros

In [ ]:
import numpy as np
ar_zero=np.zeros(4) #  for 1 dimensional array or 1 dimension matricsa

ar_zero1=np.zeros((3,4))
print(ar_zero)
print() # it gives a space in the output
print(ar_zero1)

## ones

In [ ]:
import numpy as np
ar_one=np.ones(4)

print(ar_one)
print()
ar_one1=np.ones((2,4)) # two data also add two paranthesis or bracket
print(ar_one1)


# empty

In [ ]:

ar_em=np.empty(4)
print(ar_em) ## here 1 is coming as output, that is reflacting from the  previos value
print()

print("-------------------------------------------------------")
ar_em1=np.empty((3,1))
print(ar_em1)

## range (n-1)

In [ ]:
ar_rn=np.arange(4) # range start from 0 to less than one. range means( n-1) that is 4-1 in this case
print(ar_rn)


In [ ]:
ar_rn=np.arange(1,8) # range last value is less than n-1, and 1,4) its not means 1 rows and 4 columns. it is only range startin and end(Range-1)
print(ar_rn)

# Diagonal

In [ ]:
ar_dg=np.eye(4) # 1 will arrange diagonally
print(ar_dg)

In [ ]:
ar_dg=np.eye(4,2) # Diagonally printing, 4 rows and 2 columns
print(ar_dg)

# linspace( having  equal length)

In [ ]:
ar_lin=np.linspace(0,10,num=6)  # num=6 (it is no. of obseravation randomly with equal length)
print(ar_lin)


In [ ]:
ar_lin=np.linspace(2,10,3) # (2,10,3 means  from 2 to 10 with 3 no. of observation in 1d)
print(ar_lin)

## webcube tech(L5)
## create numpy array with random numbers

## Random

##### rand()-rand function ( this function use to genrate random value between 0 to 1(only positive array)

In [ ]:
import numpy as np
var=np.random.rand(3) # it will be n no. of 1D array no. below 1
print(var)

In [ ]:
var1=np.random.rand(2,5) # 2 rows and 5 columns
print(var1)

### randn() this function gives closer to zero. may be positive or  negative aray

In [ ]:
var2=np.random.randn(4) # randn(4)/(1,4) both are same that means 1 rows and 4 columns
print(var2)

In [ ]:
var2=np.random.randn(4,8)
print(var2)

# ranf()
## [0.0,1.0)

In [ ]:
var3=np.random.ranf(4) # it gives closer to 1 not 1. from 0 to closer to1
print(var3)

# randint()

In [ ]:
var4=np.random.randint(2,7,6) # first(2 is the minimum value) 2nd(7 is the maximum value upto(less than 1,,,n-1(7-1)means till 6 will be the value) value will becount , 3rd(6 it is the total no. of obesrvation/value/no.of times))
print(var4)

# L6( data types in numpy arrays)
#### bool,float,int etc
#### .dtype(to detect  types of data types(int_int32etc))

In [ ]:

import numpy as np
var= np.array([1,2,3,4,34,34])
print("Data Types:",var.dtype)

In [ ]:
var=np.array([1.0,1.2,1.3])
print("Data types:",var.dtype)

In [ ]:
var=np.array(["a"]) #<U1-defines to string data types
print("Data types:-",var.dtype)

#### to change in desired data  types:-

In [ ]:
var=np.array([1.0,1.2,1.3],dtype=np.int8) # write the desired data type(dtype=np.int8)
print("Data types:",var.dtype)

# List  of charaters that are used  to represent dtype in Numpy:-
#### i=integer
#### b=boolean
#### u=unsigned integer
#### f= float
#### c=complex loat
#### m=timedelta, o=object,s=string,U=Unicode, 
##  desired data types can also be  convert by using short character list
# dtype="f"(as to change in float)


In [ ]:
var=np.array(["a"],dtype="f") # string never be converted in to float
print("Data types:-",var.dtype)

In [ ]:
var=np.array([1,2,3,4],dtype="f")
print("Data types:-",var.dtype)
print(var)

### Q.) we can also use data types as function
## here  we doing changes from one data to new data

In [ ]:
var1=np.array([1,2,3,4])
new=np.float32(var1)
new_one=np.int_(new)

print("Data types:-",var1.dtype)
print("Data Types:-",new.dtype)
print("DAtta types",new_one.dtype)
print(var1)
print(new)
print(new_one)

#### var4.astype(float,int_ etc)also can directly  change the data in specific data. var4(it is variable name only)

In [ ]:
var4   =np.array([1,2,3,4])
new_1=var4.astype(float)  # .astype is used to convert the data types(eg. float, integer,char ,var etc))
print(var4)
print(new_1)

In [ ]:
## till lecture 6 ,start from lecture 7 of ws cube


# ------------------------------------------------------------------------------------------------------------
# ARITHMERIC OPERATIONS
# ------------------------------------------------------------------------------------------------------------------

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
varadd=var+3 # same addition,substraction,multiplication and division is performed
print(varadd)

# ---------------------------------------
# Arith. Operations Short cut For 1D and 2D
# ---------------------------------------
### np.add(a,b)
### np.subtract(a,b)
### np.multiply(a,b)
### np.divide(a,b)
### np.mod(a/b) , for remainder
### np.power(a**b)
### np.reciprocal(1/a)

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
varadd=np.add(var,var2) # np.add(var,3) also run
print(varadd)

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
print(var+var2)  # for all arthmeitc operation,(+,-,*,/, modulours is a remainder)

# 2 D 
##### (All arithmetic operation is same as 1dimensional array)

In [ ]:
import numpy as np

var=np.array([[1,2,3,4],[1,2,3,4]])
var2=np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print() # for space 

print(var2)
print()

print("This is the sum of var and var2")
print()

print(var+var2)

 # Arithmetic Function
 # ------------------------------------------------------
 ## Axis=0(means along/in colon)
 ## Axis=1(means in Row)
 

In [ ]:
# np.min() - for minimum/lowest value of the array
# np.max()- for maximum/highest value of the array
# np.argmin()- for the index value of array
# np.sqrt()-square root of the variable

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
print("min" ,np.min(var)) # for minimum/lowest value
print("max :-" ,np.max(var))

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
print("min" ,np.min(var),np.argmin(var)) #  0 is the first index
print("max :-" ,np.max(var), np.argmax(var))# 3 is the fourth  index

In [ ]:
import numpy as np
var=np.array([[1,2,3,4],[9,8,7,5]]) # in single variable min/max will be taken from both array
print("min" ,np.min(var))
print("max " ,np.max(var))

In [ ]:
import numpy as np
var2=np.array([[1,2,3,4],[3,4,5,6]])
print(var2)
print()
print("min" ,np.min(var2,axis=1))#Axis value will be always inside np.min/max bracket
print("max :-" ,np.max(var2,axis=0))# greater value along colon
print()
print("square roots",np.sqrt(var2))# here axis=0/1 is not working

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
print("sin value of var2",np.sin(var2))
print()# for space
print("cos value of var2",np.cos(var2))
print()
print("cumsum value",np.cumsum(var2))
# cumsum- 1st value, 1st+2nd=c, c+3rd as addition one after one with total value


# Shape in nupy
### Print(var.shape)

In [ ]:
var=np.array([2,3,4,5])
print(var)
print()
print(var.shape)

In [ ]:
var=np.array([[2,3,4,5],[2,3,4,5]])
print(var)
print()
print(var.shape) # means two rowsf and 4 columns

In [ ]:
# problem =why 4 is coming in place of rows

In [ ]:
var7=np.array([[[[2,3,4,5],[5,4,5,3],[3,4,5,6],[2,3,3,5]]]])
print(var7)
print()
print("no. of array", var7.ndim)
print(var7.shape) #why 4 is coming

In [ ]:
var4=np.array([2,3,4,5],ndmin=4)
print(var4)# here only 1 row
print()

print("No of araay ",var4.ndim)
print()

print("first four 1 is rows and last 4 no. is colon",var4.shape)

In [ ]:
# Reshape

In [ ]:
import numpy as np
var01=np.array([2,3,4,5,5,5])
x=var01.reshape(2,3)# reshape size should be the total no.of array(as-here is total 6 array so it can be only reshape into 3*2 or 2*3)
print("for reshape 2*3")
print(x)
print("dimension of variable x is",x.ndim)
print()
x2=var01.reshape(3,2)
print("for reshape 3,2")
print(x2)
print("dimension of variable x2 is",x2.ndim)

In [ ]:
var02=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print()
x3=var02.reshape(1,3,4)# 1st no.(1-no. of matrix/figure), 2nd no.(3-no.of rows),3rd no.4 shows no.of columns
print(x3) # 2 rows

In [ ]:
var02=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print()
x3=var02.reshape(4,3,1)# 1st no. for matrix/figure), 2nd for rows),3rd no. for columns
print(x3) # 2 rows

### To reshape in one dimensional array
#### var.reshape(-1)  minus 1

In [ ]:
var02=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print()
x3=var02.reshape(4,3,1)# 1st no. for matrix/figure), 2nd for rows),3rd no. for columns
print(x3) # 2 rows
print()
one=x3.reshape(-1) # To reshape in to 1 dimensional array
print("this is one dimensional array")
print(one)
print(one.ndim)

# BroadCasting Numpy array

In [ ]:
import numpy as np
var=np.array([1,2,3,4])# this is 1,4 but shape give 4, only
print(var.shape) # 1,4( 1 is the dimensional and 4 is the no.of data present)
print(var)
print()
var2=np.array([[1],[2],[3],[4]]) # 4,1 means 4 dimensional with one data
print(var2.shape)
print(var2)
print()
print("sum of var and var2 is",var+var2)# for sum data input should be same

In [ ]:
x=np.array([[1],[2]])
print(x.shape)# 2 dimension array
print()
x2=np.array([[1,2,3],[1,2,3]])
print(x2.shape) # 2*3 here 2 is dimensional array and 3 is the no.of data
print("sum of x and x2 ", x+x2)
print()


print("note:- in case sum , last or unmached data ka  multiplication , data shape define krta hai ")
print("jaise:- (2,1),(2,3),in this case last 3 and 1 will multiply and will give shape of new addition data set")

# Indexing and Splicing

In [ ]:
import numpy as np
var=np.array([1,2,3,4])
print(var[1]) # for index value we can write index no. to get value.
# index always start with 0,1,2,3. 
# for negative = -1.-2,-3 etc
print(var[-1])

In [ ]:
var1=np.array([[9,8,7],[4,5,6]]) # this is 2d array for check var1.ndim
print(var1)
print()

# first value is taken as row value(0,1,2,3,etc) and second values is taken from column
print(var1[0,2]) 

# print(var1[2,1])# error because in row only till 1 index is possible

print()
print(var1[1,1]) # is at 5

In [ ]:
# indexing for 3d array
var3=np.array([[[1,2,3,4],[2,3,4,5]]])
print(var3.ndim) # to know no. of dimension as 3d
print(var3)
print()
print(var3[0,1,2]) 
# first no. 0(for the 1 dimension array where no element is found)
# 2nd no. 1(for the given rows, 0,1 only for this given array)
# 3rd no. 2(for the given columns, o,1,2,3 only for this given array)
print("for index value 0,0,0")
print(var3[0,0,0])

# Slicing
### it is define- to find a desired data set
#### it also define as to arranege the data set in desired index value
## slicing can be done with the help of index value

In [ ]:
var5=np.array([9,8,7,6,5,4,3])
 # index value    0,1,2,3,4,5,6
print(var5)
print()

print("from 8 to 4 :", var5[1:6]) # index gives value n-1 ,as (5 is the index value so array will be till 4th value)
print()
print("from 8 to end:",var5[1:]) #for end no index value is used only colon used (:)
print()
print("from start to 4",var5[:6]) # 6 is the n+1 index value because index value gives result less than one (n-1)
print()
print("from 8 to 4 with 2 space/gap",var5[1:6:2]) # first(1) and second value(6) is the index value from where to where and the last value(2) is defined about how much gap/space/jump should between no. 
print()
print("from 9 to 3, with 3 gap/space",var5[0:7:3])

In [ ]:
# now for 2d array splicing

In [ ]:
var6=np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var6)
print(var6.ndim) # to check it is 2d or not
print()
print("from 8 to 5",var6[1,1:])# for infinite data print in the row use colon:


In [ ]:
# for 3 dimension
var7=np.array([[[1,2,3,4]]])
print(var7.ndim) # to check is it 3 dimensional or not
print("from 2 to 4:", var7[0,0,1:]) # 1st 0 for 3rd dimensional ( there is no any data in the last dimension so it is taken as 0)
            # 2nd 0 is of row 1st and heere is only one row
    

In [ ]:
# Till 11th lecture start from 12 lecture

# Iteratrion in numpy array

### - it means to separate/ breake the array


In [ ]:
import numpy as np
var9=np.array([9,8,7,6,5,4])
print(var9)
print()
for i in var9:
    print(i)

 # Itteration for 2d array


In [ ]:
var11=np.array([[1,2,3,4],[1,2,3,4]])
print(var11)
for j in var11:
    print(j)

In [ ]:
# for not a row , only for column value use double for loop
var11=np.array([[1,2,3,4],[1,2,3,4]])
print(var11)
for j in var11:
    print(j)
    print()
    for k in var11:
        for l in k:
            print(l)
            
            # for 2d we uses 2 times for loop ,hence for 3d use 3 times for loop

In [ ]:
# for 3d use 3 times for loop
import numpy as np

var12=np.array([[[1,2,3,4],[1,2,3,4]]])

print(var12)
print(var12.ndim)
for j in var11:
    print(j)
    print()
    for k in var12:
        for l in k:
            for m in l:
                print(m)
           
            

In [ ]:
# Another method for Iletering the arrays by using np.nditer

In [ ]:
import numpy as np

var12=np.array([[[1,2,3,4],[1,2,3,4]]])

print(var12)
print(var12.ndim)
print()

for i in np.nditer(var12):
    print(i)

In [ ]:
# In Iletering to change the data types using np.nditer

In [ ]:
import numpy as np

var120=np.array([[[1,2,3,4],[1,2,3,4]]])

print(var120)
print(var120.ndim)
print()

for i in np.nditer(var120,flags=['buffered'],op_dtypes=["s"]):
    print(i)

In [ ]:
# for indexing of these type of data
import numpy as np

var121=np.array([[[1,2,3,4],[1,2,3,4]]])

print(var121)
for i,d in np.ndenumerate(var121):
    print(i,d)
    
    # indexing value is as like due to 3dimensional array

# copy vs view
##### Both of them have almost same work
### copy gives original data But view gives duplicated value or changes value

In [ ]:
import numpy as np
varc=np.array([1,2,3,4])
co=varc.copy()
varc[1]=11
print("varc",varc)
print("copy",co) # both gives same output
# in copy function here is no any changes takes place original value is giving

In [ ]:
import numpy as np
varv=np.array([1,2,3,4])
vi=varv.view()
varv[1]=11
print("varv",varv)
print("view",vi) # here also have the same result of variable and view
# But in view function value get changes as variable changesss

# join array  - add arrAY

In [ ]:
import numpy as np
varj=np.array([1,2,3,4])
vark=np.array([9,7,6,5])

ar=np.concatenate((varj,vark)) # concatenate means to join two array
print(ar)

In [ ]:
import numpy as np
varjk=np.array([[1,2],[3,4]])
varkj=np.array([[9,7],[6,5]])

ar1=np.concatenate((varjk,varkj),axis=0)# axis 0 means along column, and axis=1 means along rows
print(ar1)

# join BY - stack

In [ ]:
import numpy as np
va_1=np.array([1,2,3,4])
va_2=np.array([9,7,6,5])

a_1=np.stack((va_1,va_2),axis=1) # stack is also used to join
print(a_1)

In [ ]:
import numpy as np
va_10=np.array([1,2,3,4])
va_20=np.array([9,7,6,5])

a_10=np.hstack((va_10,va_20))  # use h before stack(hstack) to join  in horizontally/rows
print(a_10)

In [ ]:
import numpy as np
va_01=np.array([1,2,3,4])
va_02=np.array([9,7,6,5])

a_01=np.vstack((va_01,va_02)) # use v before stack(np.vstack) for join along column/vertically
print(a_01)
# for along high use dstack

# split array

In [ ]:
# for 1d array
j=np.array([1,2,3,4,4,5])
print(j)
newar=np.array_split(j,3)# split array in 3 array
print(newar)
print()
print(newar[0])# for single 

In [ ]:
# for 2 dimension array
import numpy as np
v1=np.array([[1,2],[3,4],[3,9]])# in 2d square bracket should be 2 at last and data set may be more than two
v2=np.array([[9,7],[6,5],[2,8]])

a_01=np.array_split(v1,3) # for v2 print in other table
print(a_01)
print()
a_011=np.array_split(v1,3,axis=1) # print in axis form
print(a_011)

In [ ]:
 # till 14 lecture start with lecture 15

# Numpy array function
### search

In [ ]:
search=np.array([1,2,3,4,4,5,6,8,8,3])

x1=np.where(search==4) # np.where gives the index value
print(x1)
x2=np.where((search%2)==0) # Remainder  value which equaly divide by 2 is 
print(x2)

In [ ]:
# searchsorted is used to find a place where number wiill adjust
sorted=np.array([1,2,3,4,5,9])
xsorted=np.searchsorted(sorted,5)# this will find a place on which index 5 will adjust
print(xsorted)

In [ ]:
sorted1=np.array([1,2,3,4,5,9])
xsorted1=np.searchsorted(sorted1,[4,5,6],side="right")# we can adjust many no. from right also, by default from left it is adjusting
print(xsorted1)

# sort - to arrange in ascending order



In [ ]:
sorted2=np.array([1,2,33,4,5,9,0])

print(np.sort(sorted2))# only print is here

In [ ]:
# same for 2d array. arranging each according rows and column 
sorted3=np.array([[1,2,33],[4,5,9]])

print(np.sort(sorted3))

In [ ]:
# string can also be sorted
string=np.array(["a","b","m","c","d"])# arrange accordinglyly
print(np.sort(string))

## Filter array

In [ ]:
filter=np.array(["a","s","b","d","f"])
f=[True,False,False,True,True]
new_a=filter[f]
print(new_a) # only true value is givingg

In [ ]:
# till 15

# Numpy array arithmetic function
### shuffle,Unique,Resize,Flatten Ravel

In [ ]:
# shufle- mix as like cards(tashf)

In [ ]:
shuf=np.array([2,3,4,5,6,1,9])
np.random.shuffle(shuf) # random value is give

print(shuf)

In [ ]:
# Unique- it gives unique value means minimise the repeatative value
un=np.array([9,3,4,5,6,7,5,6,6,6,4])
un1=np.unique(un)
un2=np.unique(un,return_index=True)# it gives index value of the array

print(un1)
print()
print(un2)
print()
un3=np.unique(un,return_index=True,return_counts=True)# for find nummber   of repetation
print(un3)

In [ ]:
 # Resize - it helps to resize the array in matrix or 2dimensional array or 3d,4d
    

In [ ]:
res=np.array([1,2,3,4,5,6,7,7,8,9,0])
r=np.resize(res,(3,4))
print(r)
print("this is 2 dimensional aray",r.ndim)

In [ ]:
# flatten- it helps to 2d in 1dimensional array


# order="f"(it takes value from column,)
# order="c"(it takes value in/from rows)

In [ ]:
z=np.resize(res,(4,3))
print(z)
print()

print("flatten",z.flatten(order="F"))# arrange in 1d accordingly column vlaue
print("flatten",z.flatten(order="C"))# arrange in 1d accordingly rows values

    

In [ ]:
# revel - helps to convert 2d in 1dimensional array


In [ ]:
print(z)
print()
print("Ravel",np.ravel(z))# defalut it gives first rows value then 2nd rows value and so onn
print("Ravel, orderr,f",np.ravel(z,order="F"))
print("Ravel, orderr,c",np.ravel(z,order="c"))

In [ ]:
# tilll 16

# Insert & Delete

In [ ]:
ins=np.array([1,2,3,4,5,7])
print(ins)
ins1=np.insert(ins,2,30)# 2 is the index valu
print(ins1)
# that means we can insert any value with the help of iNdex value

In [ ]:
ins2=np.insert(ins,(2,4), 404)# (2,4) it is the ndex value
print(ins2)


In [ ]:
ins3=np.insert(ins,(2,3),4.5)# it insert only integer not flloat value
print(ins3)

In [ ]:
ins4=np.resize(ins,(2,3))
print(ins4)
v0=np.insert(ins4,1,0,axis=0)# 0 means along rows in 1 index of rows
print(v0)

In [ ]:
# append can insert float value
# while insert can insert only integer value

In [ ]:
#  np.append is not working here

In [ ]:
# delete

In [ ]:
j=np.array([3,4,4,5])
inst0=np.delete(j,3)
print(j)
print(inst0)

# Matrix

In [ ]:
# matrix and numpy array is approx same in size nd design


In [ ]:
ma=np.matrix([[2,3,44,1],[2,2,3,4]])
print(ma)
type(ma)

In [ ]:
arr=np.array([[2,3,44,1],[2,2,3,4]])
print(arr)
type(arr) #design of both matrix and array is smilimar

### addition and substraction in Numpy array and matrix is same
### multiplication is different
 ### array= 1st row multiply by 1st row of another data
 # -----------------------------------------------
 ## Matrix multiplication is also know n as dot multiplication
 ### matrix= 1st row multiply by 1st column + 1st row multiply by 2nd column  of another data and makes 1st matrix data

In [ ]:
# addition and substraction is same in both
ar1=np.array([[2,3,44,1],[2,2,3,4]])
ar2=np.array([[2,3,44,1],[2,2,3,4]])
print(ar1+ar2)
type(ar1)


In [ ]:
mat=np.matrix([[2,3,44,1],[2,2,3,4]])
mat1=np.matrix([[2,3,44,1],[2,2,3,4]])
print(mat+mat1)

In [ ]:
mat2=np.matrix([[2,3],[2,2]])
mat3=np.matrix([[2,3],[2,2]])
print(mat2*mat3)
print("we can multiply by using dot() function :")
print(mat2.dot(mat3))

In [ ]:
mat21=np.array([[2,3],[2,2]])
mat31=np.array([[2,3],[2,2]])
print(mat21*mat31)

## Matrix function in Numpy arrays
#### 1.Transpose,  2. swapaxes, 3.Inverse, 4.Power, 5.Determinate

### 1.Transpose - Rows convert into column

In [10]:
mat2=np.matrix([[2,3],[4,0]])
print(mat2)
print()
print(np.transpose(mat2)) # transpose helps to convert rows into rows
print("shortcut to transpose is  capital :- T")
print(mat2.T)
print("----------------------------------------------")

print(np.swapaxes(mat2,0,1))# 0(rows) convert into 1(column)

[[2 3]
 [4 0]]

[[2 4]
 [3 0]]
shortcut to transpose is  capital :- T
[[2 4]
 [3 0]]
----------------------------------------------
[[2 4]
 [3 0]]


# square matrix

In [16]:
sq=np.matrix([[1,2],[3,4]])
print(sq)
print()
print(np.swapaxes(sq,0,1))# why both output is same??????????
print(np.swapaxes(sq,1,0))# column converted into Rows

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


# INVESE Matrix

In [17]:
sq1=np.matrix([[1,2],[3,4]])
print(sq1)
print()
print(np.linalg.inv(sq1)) # for inverse matrix

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
# power matrix
# has three case:- n=0,n>0,n<0
# n=0(In this we will get Identical matrix means diagonal will fill with same no. as 1)
# n>0(power multiply with matirix)
# n<0(Inverese multiply with power of matrix)

In [22]:
print(sq1)
print()
print(np.linalg.matrix_power(sq1,2))# 2(n) is greater than zero(0) so this will multiply with power and the given matrix
print()
print(np.linalg.matrix_power(sq1,-2))# -2(n) is less than 0 it will multiply with inerse of the matrix
print()
print(np.linalg.matrix_power(sq1,0)) # 0(n) is equal to zero(0)   so it wll form a identical matrix


[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]

[[1 0]
 [0 1]]


## Determinant
### function of Determinnat is   np.linalg.det(var)
### for determinat +,-,+,- aise eski sum chalti hai 
####  Note- For square matrix two dimensional value of matrix should be shame

In [26]:
print(sq1)
print()
print(np.linalg.det(sq1)) # this will find the  determinant of matrix

sq2=np.matrix([[1,2,3],[2,32,44],[1,2,3]])
print(np.linalg.det(sq2)) # determinant of square matrix is zero

[[1 2]
 [3 4]]

-2.0000000000000004
0.0
